@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nModel" as Model

Class ModelManager

Class Contact

Class Meeting


Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

ModelManager .up.|> Model

ModelManager --> "~* filtered" Contact
ModelManager --> "~* filtered" Meeting
@enduml
